### ISSUE TITLE
Sublime is out of focus after switching projects

### ISSUE THREAD

**Issue by ofirgall** [randy3k/AutoMatchEnabled#1]
Hey, I very like the idea and the plugin itself, but i got a problem after i quick switch between projects the sublime is getting out of focused, to get it on focus i need to click on the sublime text with my mouse and its very annoy me, if you could resolve it I would be happy.

**Comment by randy3k** [comment]
I guess you hv posted in a wrong repo.

**Comment by ofirgall** [comment]
Whoops... Sorry
בתאריך 8 במרץ 2016 06:03,‏ "Randy Lai" notifications@github.com כתב:
